index:
   path: /
   controller: App\Controller\GalleryController::index

save:
   path: /gallery/save
   controller: App\Controller\GalleryController::save

image_show:
   path: /image/{id}
   controller: App\Controller\GalleryController::show

image_new:
   path: /gallery/new
   controller: App\Controller\GalleryController::create

image_delete:
   path: /image/delete/{id}
   controller: App\Controller\GalleryController::delete

edit_image:
   path: /image/edit/{id}
   controller: App\Controller\GalleryController::update
